### ISSUE TITLE
ISSUE#3.1 - RANI - ISSUE SELECTION - Add Shuffling Algorithm

### ISSUE THREAD

**Issue by ba-00001** [CIS3590-G1B/GROUP-1B-Java#2]
### What would you like to Propose?

@Vasto-Lorde999  UPDATE THIS SECTION 

### Issue details

@Vasto-Lorde999 UPDATE THIS SESSION

### Additional Information

@Vasto-Lorde999 UPDATE THIS SESSION

**Comment by Vasto-Lorde999** [comment]
**What Would you like to Propose?**
- Travelling Salesman Problem

**Issue Details**
- Given a matrix with distances and cities, provide an algorithm that finds the shortest possible route through every city

**Comment by RanyM-999** [comment]
**What Would you like to Propose?**

- Add Shuffling Algorithm

**Issue Details**

- Develop a function that accepts a list and returns a shuffled version.
- Ensure uniform distribution of permutations by leveraging a reliable randomization method.

**Comment by RanyM-999** [comment]
Add Shuffling Algorithm

What Would you like to Propose?
I would like to propose the addition of the Shuffling Algorithm (such as Fisher-Yates) to the repository. This algorithm would be useful for providing a randomized order of the elements in a given list, ensuring randomness. Implementing this in Java would prove to be a useful addition to the existing repository.

Issue Details
The Shuffling Algorithm works by randomizing elements in a list, effectively destroying any previous orders and making every possible order of elements equal in likelihood to one another. The Fisher-Yates algorithm has a time complexity of O(n) and space complexity of O(1).

Additional Information
The proposed implementation will be using the Fisher-Yates Algorithm in order to shuffle finite sequences and order elements by picking them from a list one by one until there are none left, therefore creating unbiased permutations where each possible combination is as likely as another.

[FEATURE REQUEST]: Add Shuffling Algorithm https://github.com/TheAlgorithms/Java/issues/5635
